msgid ""
msgstr ""
"Project-Id-Version: svs 0.1.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-06-14 11:20+0200\n"
"PO-Revision-Date: 2016-06-14 14:51+0200\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"X-Generator: Poedit 1.8.7.1\n"
"Last-Translator: Mihály Héder <mihaly.heder@sztaki.mta.hu>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"Language: hu\n"
"X-Poedit-SourceCharset: UTF-8\n"

#: src/svs/inacademia_server.py:194 src/svs/inacademia_server.py:211
#: src/svs/inacademia_server.py:247 src/svs/inacademia_server.py:260
#: src/svs/inacademia_server.py:273
msgid "Page not found."
msgstr "Az oldal nem található."

#: src/svs/inacademia_server.py:344
msgid "Domain"
msgstr "Honos intézmény"

#: src/svs/inacademia_server.py:349
msgid "Country"
msgstr "Ország"

#: src/svs/inacademia_server.py:373
msgid "Affiliation"
msgstr "Affiliáció"

#: src/svs/inacademia_server.py:373
msgid "Identifier"
msgstr "Azonosító"

#: src/svs/inacademia_server.py:373
msgid "Authentication time"
msgstr "Az authentikáció ideje"

#: src/svs/inacademia_server.py:410 src/svs/oidc.py:92
msgid ""
"We could not complete your validation because an error occurred while "
"handling your request. Please return to the service which initiated the "
"validation request and try again."
msgstr ""
"Nem tudtuk validálni az ön kapcsolatát a honos intézménnyel, mert hiba "
"történt a kérés feldolgozása közben. Kérem, térjen vissza a "
"szolgáltatáshoz amely a validációt kezdeményezte és próbálja újra."

#: src/svs/oidc.py:154
msgid ""
"The authentication request could not be processed. Please return to the "
"service which initiated the validation request and try again."
msgstr ""
"Az azonosítási kérés nem feldolgozható. Kérem, térjen vissza a "
"szolgáltatáshoz amely a validációt kezdeményezte és próbálja újra."

#: src/svs/oidc.py:161
msgid "Configuration error for the service."
msgstr "Konfigurációs hiba a szolgáltatásban."

#: src/svs/user_interaction.py:49
msgid "{client_name} requires the information below to be transferred:"
msgstr "{client_name} az alábbi információ átadását igényli:"

#: src/svs/templates/consent.mako:38
msgid "Consent - Your consent is required to continue."
msgstr "Hozzájárulás - a folytatáshoz a hozzájárulása szükséges"

#: src/svs/templates/consent.mako:61
msgid "Ok, accept"
msgstr "Ok, elfogadom"

#: src/svs/templates/consent.mako:66
msgid "No, cancel"
msgstr "Nem, Mégsem"

#: src/svs/templates/consent.mako:81 src/svs/templates/error.mako:68
msgid "Terms of service"
msgstr "A szolgáltatás felhasználási feltételei"

#: src/svs/templates/error.mako:26
msgid "Error - An error occurred."
msgstr "Hiba - hiba történt"

#: src/svs/templates/error.mako:44
msgid "message"
msgstr "üzenet"

#: src/svs/templates/error.mako:53
msgid "Timestamp"
msgstr "Időbélyeg"

#: src/svs/templates/error.mako:58
msgid "Error id"
msgstr "Hiba azonosító"
