msgid ""
msgstr ""
"Project-Id-Version: InAcademia 0.1.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-06-30 09:04+0300\n"
"PO-Revision-Date: 2016-06-30 09:21+0300\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"X-Generator: Poedit 1.8.8\n"
"Last-Translator: Andrej Šliamin <Andrej.Sliamin@ku.lt>\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"(n%100<10 || n%100>=20) ? 1 : 2);\n"
"Language: lt_LT\n"

#: src/svs/inacademia_server.py:194 src/svs/inacademia_server.py:211
#: src/svs/inacademia_server.py:247 src/svs/inacademia_server.py:260
#: src/svs/inacademia_server.py:273
msgid "Page not found."
msgstr "Puslapis nerastas."

#: src/svs/inacademia_server.py:344
msgid "Domain"
msgstr "Domenas"

#: src/svs/inacademia_server.py:349
msgid "Country"
msgstr "Šalis"

#: src/svs/inacademia_server.py:373
msgid "Affiliation"
msgstr "Darbo vieta"

#: src/svs/inacademia_server.py:373
msgid "Identifier"
msgstr "Identifikatorius"

#: src/svs/inacademia_server.py:373
msgid "Authentication time"
msgstr "Identivikavimo laikas"

#: src/svs/inacademia_server.py:410 src/svs/oidc.py:92
msgid ""
"We could not complete your validation because an error occurred while "
"handling your request. Please return to the service which initiated the "
"validation request and try again."
msgstr ""
"Mes negalėjome užbaigti jūsų tikrinimo, kadangi tvarkant jūsų užklausą "
"įvyko klaida. Prašome grįžti į jūsų sritį, iš kurios buvo pradėta "
"patvirtinimo užklausa, ir bandykite dar kartą."

#: src/svs/oidc.py:154
msgid ""
"The authentication request could not be processed. Please return to the "
"service which initiated the validation request and try again."
msgstr ""
"Identifikavimo užklausos apdoroti nepavyko. Prašome grįžti į jūsų "
"sritį, iš kurios buvo pradėta patvirtinimo užklausa, ir bandykite dar "
"kartą."

#: src/svs/oidc.py:161
msgid "Configuration error for the service."
msgstr "Paslaugos konfigūracijos klaida."

#: src/svs/user_interaction.py:49
msgid "{client_name} requires the information below to be transferred:"
msgstr ""
"{client_name} vartotojui reikalinga perduoti žemiau pateiktą "
"informaciją:"

#: src/svs/templates/consent.mako:38
msgid "Consent - Your consent is required to continue."
msgstr "Sutikimas - Kitam veiksmui yra reikalingas jūsų sutikimas"

#: src/svs/templates/consent.mako:61
msgid "Ok, accept"
msgstr "Gerai, sutinku"

#: src/svs/templates/consent.mako:66
msgid "No, cancel"
msgstr "Ne, atšaukti"

#: src/svs/templates/consent.mako:81 src/svs/templates/error.mako:68
msgid "Terms of service"
msgstr "Paslaugos tiekimo sąlygos"

#: src/svs/templates/error.mako:26
msgid "Error - An error occurred."
msgstr "Klaida - Įvyko klaida."

#: src/svs/templates/error.mako:44
msgid "message"
msgstr "pranešimas"

#: src/svs/templates/error.mako:53
msgid "Timestamp"
msgstr "laiko žyma"

#: src/svs/templates/error.mako:58
msgid "Error id"
msgstr "Klaidos id"
